from pydantic import BaseModel, Field
from typing import Annotated, List, Optional, Dict, Any
from langgraph.graph import add_messages
from langchain_core.messages import BaseMessage
from schema.intent_classification_schema import IntentClassifierSchema
from schema.planner_schema import PlanStep
from schema.follow_up_schema import FollowUpSchema





class AgentState(BaseModel):
    messages: Annotated[List[BaseMessage], add_messages] = Field(default_factory=list, description="Messages of the chatbot") 
    
    current_user_query: Optional[str] = None
    last_user_query: Optional[str] = None
    resolved_query: Optional[str] = None
    
    last_objective: Optional[str] = None
    last_result_summary: Optional[str] = None
    last_row_count: Optional[int] = None
    
    followup: Optional[FollowUpSchema] = None
    
    
    intent_result: Optional[IntentClassifierSchema] = Field(description="Intent result from the intent classification node to provide information for query planning", default=None)
    table_schema: Optional[str] = Field(default=None, description="Tables Schema information for the give query")
    plan: List[PlanStep] = Field(default=[],description="Ordered list of PlanStep objects produced by the query planner.")
    plan_index: int = Field(default=0,description="Index of the currently executing step in the plan list.")
    completed_steps: List[Dict[str, Any]] = Field(default_factory=list, description="A list to store information about completed steps, such as their sql and results.")
    sql: Optional[str] = Field(default=None, description="The SQL query generated by the agent, if applicable.")
    sql_executed: Optional[bool] = Field(default=False, description="If the sql is executed by the executor or not.")
    raw_data: Optional[Dict[str, Any]] = Field(default=None, description="Any raw data or additional information relevant to the agent's state.")
    validation_feedback: Optional[Dict[str,Any]] = Field(default=None, description="Validation feedback from the raw data and the given query.")
    analysis: Optional[str] = Field(default=None, description="Any analysis or insights derived from the conversation or data.")
    chart_base64: Optional[str] = Field(default=None, description="A base64-encoded string representing a chart or visualization generated by the agent.")
    narrative: Optional[str] = Field(default=None, description="A narrative or explanation generated by the agent based on the conversation or data.")
    error: Optional[str] = Field(default=None, description="Any error messages or issues encountered by the agent during processing.")
    retry_count: int = Field(default=0, description="The number of times the agent has attempted to retry an action or response.")